### ISSUE TITLE
compile fails in xenial

### ISSUE THREAD

**Issue by Ntemis** [aweatherguy/Katiana#1]
cc ValidateUsbHdwrSerial.c -o TmpExec.exe
./TmpExec.exe

---------- Validating USB Serial Number (Strict) ----------

----------      USB Serial Number is  Valid     ----------

 [INFO]    : Begin compilation of project "Katiana"...

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "Katiana.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega32u4 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=8000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/ -DBOOT_START_ADDR=0x7000 -I. -I../../LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_USER -DF_USB=8000000UL  -MMD -MP -MF obj/Katiana.d Katiana.c -o obj/Katiana.o
Katiana.c:111:16: error: variable ‘avrSignature’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
 static uint8_t avrSignature[3] PROGMEM = { AVR_SIGNATURE_3, AVR_SIGNATURE_2, AVR_SIGNATURE_1 };
                ^
Katiana.c:117:16: error: variable ‘softwareIdentifier’ must be const in order to be put into read-only section by means of ‘__attribute__((progmem))’
 static uint8_t softwareIdentifier[7] PROGMEM = SOFTWARE_IDENTIFIER;
                ^
../../LUFA/Build/DMBS/DMBS/gcc.mk:216: recipe for target 'obj/Katiana.o' failed
make: *** [obj/Katiana.o] Error 1

**Comment by valentinpy** [comment]
Try using this fix: https://github.com/m-kozlowski/Katiana/commit/0a437126395ab8b87e1b40c54783427442a3befe

**Comment by Ntemis** [comment]
thank you
